### PR TITLE
docs: update getting-started/svelte.md

### PR DESCRIPTION
**Pull request by shinokada**
Update getting-started/svelte.md

### CODE REVIEW

**Comment by Steellgold** [comment]
https://github.com/themesberg/flowbite/pull/446

**Comment by zoltanszogyenyi** [comment]
Thanks for the PR! Can we please add a few more examples on how to use the Flowbite Svelte components? It should help new users onboard with the Flowbite Svelte library more than just showcasing an alert. For example, we could write a short guide on how to leverage interactivity of a modal, dropdown, or navbar. Thanks.

**Comment by shinokada** [comment]
Can we add the link to https://flowbite-svelte.com/ for more details?

**Comment by zoltanszogyenyi** [comment]
We can definitely add Flowbite Svelte for more details, however, because a large part of the text has been removed it could impact SEO hence why I suggested adding some examples on how to use it directly on the page to make up for the lost content. I can add these examples myself it's just that right now I'm working on a Phoenix Framework integration guide.

**Comment by shinokada** [comment]
Ok, I will add more content.

**Comment by zoltanszogyenyi** [comment]
Any update on this one? @shinokada

**Comment by shinokada** [comment]
Please see https://github.com/themesberg/flowbite/pull/503

**Pull request closed without merging**
