### PR TITLE
Support phoenix liveview

### LINKED ISSUE #486: Setup Flowbite to work with Phoenix LiveView
I have gone through the guide for setting up Flowbite in Phoenix [here](https://flowbite.com/docs/getting-started/phoenix/), however perhaps the guide might need to be updated.
This issue is similar to #88. Due to the way Phoenix LiveView works, Flowbite components that require javascript stop working when to navigate between LiveViews. This is because LiveView uses a Websocket, does not do a full page reload but just patching the DOM, therefore it does not dispatch  `load` event which should initialize Flowbite javascript after a page is loaded.

There are some ways to fix this:

1. Update the `assets/js/app.js` to dispatch the `load` event once the LiveView is loaded:
```diff
window.addEventListener("phx:page-loading-stop", _info =>
    topbar.hide()
+    window.dispatchEvent(new Event("load"), {
+        bubbles: true,
+        cancelable: true
+    })
})
```
2. Similar to the Flowbite js(`/node_modules/flowbite/lib/esm/index.turbo.js`) for Turbo, we can have js file specifically for Phoenix LiveView. In the file we have something like this:
```diff
// setup events for data attributes
-var events = new Events('load', [
+var events = new Events('phx:page-loading-stop', [
    initAccordions,
    initCollapses,
    initCarousels,
    initDismisses,
    initDropdowns,
    initModals,
    initDrawers,
    initTabs,
    initTooltips,
    initPopovers,
    initDials,
]);
events.init();
```

I have tested both approaches and they work, though for now I think the first approach would suffice, and perhaps included in the setup guide for Phoenix. 
I have attached a gif illustrating the issue where the Flowbite components stop working when I navigate between LiveViews and how Bootstrap components worked without making changes in `app.js`.
demo

### PR DESCRIPTION
**Pull request by jmnda-dev**
This PR resolves #486

- [x] add `index.phoenix.ts` for initializing Flowbite components in Phoenix LiveViews and regular views
- [x] update configs to build for `index.phoenix.ts`
- [x] update the docs
- [x] add instructions for setup the `flowbite-datepicker`

### CODE REVIEW

**Comment by jmnda-dev** [comment]
The PR is work in progress, will continue tomorrow, please leave feedback as well.

**Comment by jmnda-dev** [comment]
> So we need both the load and phx:page-loading-stop events, right?

Yeah, that way it will work for both LiveViews and regular Views

**Comment by jmnda-dev** [comment]
I have added instruction for including the javascript file via CDN, though I have some questions:

1. How do you handle publishing the javascript files to the CDN, and are going to publish `flowbite.phoenix.js` to a CDN? 

2. And also regarding building Flowbite locally, I used `npm run build:npm` command, it generated a `dist` and `lib` folders which I copied to the `flowbite` folder in `assets/node_modules/flowbite`, in order to test the built files, am not sure if this is a right way. My question is how do you test your Flowbite builds?

**Comment by jmnda-dev** [comment]
@zoltanszogyenyi  I have not added a datepicker javascript file for Phoenix, I feel it's not necessary, however I have added instructions for setting up the datepicker using `flowbite-datepicker`.

**Comment by zoltanszogyenyi** [comment]
Hey @jmnda-dev,

Thanks for the contribution.

1. Files will be published by me via NPM and this will be reflected either on UNPKG or CDNJS shortly after -> everything that is generated inside the `dist/` and `lib/` folders go there.
2. That is the right way - make sure that both the minified and non minified + mapping files are correctly generated and copied over and that will work good enough -> you can change the name of the package.json file and publish it yourself on a test package and use the automatically generated UNPKG CDN links to test livewire.

Cheers,
Zoltan

**Comment by jmnda-dev** [comment]
Hi @zoltanszogyenyi, I make a slight change to the Phoenix docs. As for now the generated files, I have checked everything and all looks good on my end.

**Comment by gsperka** [comment]
@jmnda-dev  - thanks for looking into this. I am actually running into the same exact problem with LiveView.  

@zoltanszogyenyi - any update on this?

**Comment by jmnda-dev** [comment]
> @jmnda-dev - thanks for looking into this. I am actually running into the same exact problem with LiveView.
@gsperka  If you haven't found a solution yet, you can look at a quick fix I mentioned in this issue #486 

The work on the PR is done, waiting feedback from @zoltanszogyenyi. If you have any suggestions on this PR let me know.

**Comment by zoltanszogyenyi** [comment]
Hey @jmnda-dev,

I'll try to include this in the weekend for the next release! Looks pretty good at a first glance.

Cheers,
Zoltan

**Comment by selimyoussry** [comment]
Hey @jmnda-dev , thanks a lot for the work.

@zoltanszogyenyi for what it's worth I've patched our app (which is on Phoenix Liveview + Tailwind latest version) with @jmnda-dev 's work (see below) and FlowbiteJS now works for me. Until then I basically had to deactivate all your JS and kind of reimplement it with custom JS. Not ideal!

Thanks both and have a good Sunday :).

Here's what I did based on the work of this PR

In `app.js`
```javascript
import './flowbite'
```
instead of directly doing `import 'flowbite'`

In `flowbite.ts`

```javascript
/*
  Fetched code from https://github.com/themesberg/flowbite/pull/487
  to support LiveView re-renders and navigation.
  
  Without this patch, Flowbite JS is unusable within LiveView. 
*/

import 'flowbite';
import Events from 'flowbite/lib/esm/dom/events';

// core components
import {
    initAccordions, initCarousels, initCollapses, initDials, initDismisses, initDrawers, initDropdowns,
    initModals, initPopovers, initTabs, initTooltips
} from 'flowbite';

const liveViewLoadEvents = new Events('phx:page-loading-stop', [
    initAccordions,
    initCollapses,
    initCarousels,
    initDismisses,
    initDropdowns,
    initModals,
    initDrawers,
    initTabs,
    initTooltips,
    initPopovers,
    initDials,
]);
liveViewLoadEvents.init();

const regularViewLoadEvents = new Events('load', [
    initAccordions,
    initCollapses,
    initCarousels,
    initDismisses,
    initDropdowns,
    initModals,
    initDrawers,
    initTabs,
    initTooltips,
    initPopovers,
    initDials,
]);
regularViewLoadEvents.init();
```

**Comment by zoltanszogyenyi** [comment]
Merged <3.

Will release v1.6.5 soon - will let you peeps know.

**Comment by jmnda-dev** [comment]
Thank you @zoltanszogyenyi

**Pull request merged**
