### PR TITLE
add navbar rtl example

### PR DESCRIPTION
**Pull request by motahharm**
Hi @zoltanszogyenyi and Flowbite community

I made a RTL navigation bar.
Because LTR navigation bars in RTL languages ​​did not work properly and had problems.

Screenshot 2022-02-07 155937

Anyway, thank you for Flowbite

### CODE REVIEW

**Comment by zoltanszogyenyi** [comment]
Hey @motahharm,

Thanks for the contribution!

I can't approve this PR because we would like to use the recommended `rtl:` variants from Tailwind CSS: https://tailwindcss.com/docs/hover-focus-and-other-states#rtl-support

If you make our current Navbar or components compatible for RTL using the recommended methodology, I'll be more than happy to approve to PR's.

Thanks!

**Comment by motahharm** [comment]
Hey @zoltanszogyenyi 

Yes, that's better.

Should I add to all the navigation bars or just one ??

**Comment by zoltanszogyenyi** [comment]
Try adding it to one of them and after that, I'll check it out.

At some point, we would like to offer RTL support to all components.

**Comment by motahharm** [comment]
@zoltanszogyenyi 

Can you check edits??

it is ok or not??

Screenshot 2022-02-07 180444

**Comment by alimoslem** [comment]
@motahharm 
thanks bro.
it is good.
can you add rtl support for all of flowbite components??

and thanks @zoltanszogyenyi

**Comment by motahharm** [comment]
hey @alimoslem 
thanks too

me and @zoltanszogyenyi trying to add rtl support for all of flowbite components.

@zoltanszogyenyi wants Flowbite to support RTL pages soon, and I'll help him.

Right now I've added support for the navigation bar RTL and he wants to check this out and then update Flowbite

**Review by ayushete02 — APPROVED** [review]

**Comment by zoltanszogyenyi** [comment]
We have official support for RTL on all Flowbite components: https://flowbite.com/docs/customize/rtl/

**Pull request closed without merging**
