### PR TITLE
Update Doc: SvelteKit 1.0

### PR DESCRIPTION
**Pull request by Steellgold**

### CODE REVIEW

**Comment by zoltanszogyenyi** [comment]
Hey @Steellgold - thanks for the contribution!

@shinokada can you please check this out if it's valid? Thanks!

**Comment by shinokada** [comment]
It is ok to be merged.

**Comment by shinokada** [comment]
I will update the page and create a PR.

**Comment by zoltanszogyenyi** [comment]
Hello @Steellgold @shinokada,

There are two PR's for the Svelte Kit documentation - which one should I merge?

Cheers,
Zoltan

**Comment by shinokada** [comment]
You need to merge, https://github.com/themesberg/flowbite/pull/455.

**Pull request closed without merging**
